- name: Deploy Frontend to a node
  user: root
  hosts: $target
  tasks:
    - include: ../global/global.yml

    - name: Get SBT rpm
      command: creates=/root/sbt.rpm curl -Lo /root/sbt.rpm http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.12.3/sbt.rpm

    - name: Install Frontend dependencies
      yum: state=present name=$item
      with_items:
        - collectd-web
        - nginx
        - java-1.7.0-openjdk
        - java-1.7.0-openjdk-devel
        - /root/sbt.rpm

    # These are separate from the above so that they're easier to split off
    # when BCS runs on a non-frontend node.
    - name: Install BCS dependencies
      yum: state=present name=$item
      with_items:
        - policycoreutils-sandbox
        - java-1.7.0-openjdk
        - scala
        - ruby
        - gcc
        - gcc-c++
        - Io-*
      tags:
        - bcs-dependencies

    - name: Create an evalso user
      command: creates=/home/evalso useradd evalso

    - name: Put nginx proxy config in place
      template: src=files/nginx/frontend.conf dest=/etc/nginx/conf.d/frontend.conf

    - name: Pull latest Frontend code
      git: repo=git://github.com/eval-so/frontend.git dest=/srv/www/frontend

    - name: Chown Frontend code to evalso
      command: chown -R evalso.evalso /srv/www/frontend

    #- name: Update Frontend dependencies
    #  shell: chdir=/srv/www/frontend _JAVA_OPTIONS="-Xms256m -Xmx512m" sbt update

    - name: Start services
      shell: systemctl start $item.service && systemctl enable $item.service
      with_items:
        - nginx

    - name: Set iptables
      template: src=files/iptables dest=/etc/sysconfig/iptables

    - name: Restart iptables
      command: service iptables restart
