- name: Deploy Frontend to a node
  user: root
  hosts: $target
  tasks:
    - name: Get SBT rpm
      command: creates=/root/sbt.rpm curl -Lo /root/sbt.rpm http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.12.3/sbt.rpm

    - name: Install Frontend dependencies
      yum: state=present name=$item
      with_items:
        - denyhosts
        - python-bucky
        - tmux
        - git
        - nginx
        - java-1.7.0-openjdk
        - java-1.7.0-openjdk-devel
        - /root/sbt.rpm

    # These are separate from the above so that they're easier to split off
    # when BCS runs on a non-frontend node.
    - name: Install BCS dependencies
      yum: state=present name=$item
      with_items:
        - policycoreutils-sandbox
        - java-1.7.0-openjdk
        - scala
        - ruby
        - gcc
        - gcc-c++
      tags:
        - bcs-dependencies

    - name: Put nginx proxy config in place
      template: src=files/nginx/frontend.conf dest=/etc/nginx/conf.d/frontend.conf

    - name: Pull latest Frontend code
      git: repo=git://github.com/eval-gd/frontend.git dest=/srv/www/frontend

    - name: Nuke .sbt/staging to pull latest git dependencies (SBT bug)
      command: rm -rf /root/.sbt/staging

    - name: Update Frontend dependencies
      shell: chdir=/srv/www/frontend _JAVA_OPTIONS="-Xms256m -Xmx512m" sbt update

    - name: Configure Bucky
      template: src=files/bucky/bucky.conf dest=/etc/bucky/bucky.conf

    - name: Add Bucky to systemd
      template: src=files/bucky/bucky.service dest=/etc/systemd/system/bucky.service

    - name: Start services
      shell: service $item start && chkconfig $item on
      with_items:
        - nginx
        - denyhosts
        - bucky

    - name: Set iptables
      template: src=files/iptables dest=/etc/sysconfig/iptables
