language: ruby
rvm:
  - 1.9.3
before_install:
  - gem update --system
  - gem install puppet puppet-lint
script: rake lint
notifications:
  irc: "irc.freenode.net#breakpoint-eval"

  webhooks:
    - "http://rcmp.tenthbit.net/irc.tenthbit.net/programming"
