# Mostly copied from
# http://infrastructure.fedoraproject.org/cgit/ansible.git/tree/playbooks/vhost_update.yml
- name: Update the system
  hosts: "{{ target }}"
  accelerate: true
  gather_facts: False
  user: root

  tasks:
  - name: expire-caches
    command: yum clean expire-cache
    
  - name: yum -y update
    command: yum -y update
    async: 7200
    poll: 15

- name: run rkhunter if installed
  hosts:  "{{ target }}"
  accelerate: true
  user: root

  tasks:
  - name: check for rkhunter
    command: /usr/bin/test -f /usr/bin/rkhunter
    register: rkhunter
    ignore_errors: true
  
  - name: run rkhunter --propupd
    command: /usr/bin/rkhunter --propupd
    when: rkhunter|success
