- name: Prepare a CI node for imaging [Do not use this for normal test running]
  user: root
  hosts: $target
  tags:
    - image
  tasks:
    - name: Update packages
      command: yum -y update

    - name: Enable selinux
      lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=enforcing

    - name: Install Fedora 18 key
      command: rpm --import https://fedoraproject.org/static/DE7F38BD.txt

    - name: Update yum
      command: yum -y update yum

    - name: Clean yum caches
      command: yum clean all

    - name: Update to Fedora 18
      command: yum -y --releasever=18 --disableplugin=presto distro-sync

    - name: Reboot into Fedora 18
      command: /sbin/reboot
      ignore_errors: yes

    - name: Wait for it to come back
      local_action: wait_for host=$target port=22 state=stopped
      local_action: wait_for host=$target port=22

    - name: Get SBT rpm
      command: creates=/root/sbt.rpm curl -Lo /root/sbt.rpm http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.12.3/sbt.rpm

    - name: Install deps needed for most things
      yum: state=present name=$item
      with_items:
        - java-1.7.0-openjdk
        - java-1.7.0-openjdk-devel
        - git
        - httpie
        - /root/sbt.rpm

- name: Prepare a CI node
  user: root
  hosts: $target
  tags:
    - test
  tasks:
    - name: Update packages
      command: yum -y update

      # Things added here should be added to 'image' above, and should be removed
      # when a new image is created (usually once per Fedora release).
    #- name: Install deps missing from the image
    #  yum: state=present name=$item
    #  with_items:

    - name: Create an evalso user
      command: creates=/home/evalso useradd evalso

- name: Tests for Frontend
  user: root
  sudo: yes
  sudo_user: evalso
  hosts: $target
  tags:
    - frontend
  tasks:
    - name: Pull latest Frontend code
      git: repo=git://github.com/eval-so/frontend.git dest=/home/evalso/frontend version=$branch

    - name: Run tests
      shell: chdir=/home/evalso/frontend ./.run-tests.sh
      ignore_errors: yes

- name: Tests for minibcs
  user: root
  hosts: $target
  tags:
    - minibcs
  tasks:
    - name: Install BCS dependencies
      yum: state=present name=$item
      with_items:
        - policycoreutils-sandbox
        - java-1.7.0-openjdk
        - scala
        - ruby
        - gcc
        - gcc-c++
        - Io-*
        - php

- name: Tests for minibcs
  user: root
  sudo: yes
  sudo_user: evalso
  hosts: $target
  tags:
    - minibcs
  tasks:
    - name: Pull latest minibcs code
      git: repo=git://github.com/eval-so/minibcs.git dest=/home/evalso/minibcs version=$branch

    - name: Run tests
      shell: chdir=/home/evalso/minibcs ./.run-tests.sh
      ignore_errors: yes
