- name: Make sure selinux is enforcing
  selinux: state=enforcing policy=targeted

- name: Make sure selinux is permanently enforcing
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=enforcing

- name: Install dependencies
  yum: state=present name={{ item }}
  with_items:
    - selinux-policy-sandbox
    - cruncher-policy
    - policycoreutils-sandbox
    - java-1.7.0-openjdk
    - ruby
    - gcc
    - gcc-c++
    - Io-*
    - php
    - perl
    - factor
    - chicken
    - jruby
    - lci
    - python
    - python3
    - lua
    - mlton
    - mono-core
    - mono-basic
    - fsharp
    - gnu-smalltalk
    - ghc
    - elixir
    - rust
    - idris
    - rakudo-star
    - clojure
    - scala
